apiVersion: v1
kind: PersistentVolume
metadata:
  name: semaphore-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8server/Semaphore_Ansible_Controller/semaphore-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250  # Use your MetalLB-assigned IP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: semaphore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:latest
          ports:
            - containerPort: 3000
          env:
            - name: SEMAPHORE_DB_DIALECT
              value: postgres
            - name: SEMAPHORE_DB_HOST
              value: postgres
            - name: SEMAPHORE_DB_PORT
              value: "5432"
            - name: SEMAPHORE_DB_USER
              value: semaphore
            - name: SEMAPHORE_DB_PASS
              value: semaphore123
            - name: SEMAPHORE_DB
              value: semaphore
            - name: SEMAPHORE_ADMIN
              value: admin
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: admin123
            - name: SEMAPHORE_ADMIN_NAME
              value: "Admin"
            - name: SEMAPHORE_ADMIN_EMAIL
              value: admin@example.com
            - name: SEMAPHORE_PORT
              value: "3000"
          volumeMounts:
            - name: semaphore-data
              mountPath: /etc/semaphore
      volumes:
        - name: semaphore-data
          persistentVolumeClaim:
            claimName: semaphore-pvc
